# Generated by Django 3.0.5 on 2020-04-15 09:06

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DealersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('dl1', models.CharField(max_length=15, unique=True)),
                ('dl2', models.CharField(max_length=15, unique=True)),
                ('tin', models.CharField(max_length=15, unique=True)),
                ('person_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ComplteStockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(max_length=30)),
                ('price_per_unit', models.FloatField()),
                ('manf_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('margin', models.CharField(max_length=20)),
                ('cgst', models.CharField(max_length=20)),
                ('sgst', models.CharField(max_length=20)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.DealersInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Billings',
            fields=[
                ('bill_number', models.AutoField(primary_key=True, serialize=False)),
                ('bill_items', jsonfield.fields.JSONField()),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bill_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Person')),
            ],
        ),
    ]
